name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cognome_nome_laurea_aa.tex
          
      - name: Archive PDFs
        uses: actions/upload-artifact@v3
        with:
          name: pdfs
          path: CancianiLorenzo-A tiny network stack for battery-free communication.pdf

      - name: Upload to git
        run: |
          git config --local user.email "cancianilorenzo@gmail.com"
          git config --local user.name "Lorenzo"
          git commit -m "Compiled from GitHub actions" -a
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
        
