name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cognome_nome_laurea_aa.tex
          
      - name: Archive PDFs
        uses: actions/upload-artifact@v2
        with:
          name: pdfs
          path: |
            *.pdf
